import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";


//  NEXT JS 15.0.4
import "./globals.css";

const inter = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "The Most Closer Factory",
  description: "Generated by create BootsDev-X",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider >
      <html lang="en">
        <body className={`${inter.className} flex justify-center h-screen  items-center`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
